name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest

    env:
      Solution_Name: Source/Apskaita5vNext.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: dotnet restore $env:Solution_Name

      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=Release  /v:diag

      - name: Archive build output
        if: ${{ matrix.configuration == 'Release' }}
        run: |
          mkdir -p output
          cp -r Source/bin/Release/* output/
